Refectored Model Patcher Class
foundation-model-stack/fms-acceleration pull request #55
Opened 2024-07-18 11:01 UTC by achew010

## Description

This PR addresses #44, it moves the ModelPatcher class to the Framework plugin so that all plugin patches can be managed and maintained under a common framework.

### Items
- Move ModelPatcher class to `fms-acceleration`
- Replace local plugin patches with ModelPatcher functions
- Unit tests to test ModelPatcher functionality

### Tests
#### Matches with previous patching Implementation for FOAK 
```
export CUDA_VISIBLE_DEVICES=0
export ACCELERATION_FRAMEWORK_CONFIG_FILE=/workspace/fms-acceleration/scripts/benchmarks/../../sample-configurations/accelerated-peft-autogptq-foak-sample-configuration.yaml
python -m tuning.sft_trainer --model_name_or_path TheBloke/Mistral-7B-v0.1-GPTQ --packing True --max_seq_len 4096 --learning_rate 2e-4 --fp16 True --torch_dtype float16 --peft_method lora --r 16 --lora_alpha 16 --lora_dropout 0.1 --target_modules q_proj k_proj v_proj o_proj --use_flash_attn True --response_template '
### Response:' --dataset_text_field output --include_tokens_per_second True --num_train_epochs 1 --gradient_accumulation_steps 1 --gradient_checkpointing True --evaluation_strategy no --save_strategy no --weight_decay 0.01 --warmup_steps 10 --adam_epsilon 1e-4 --lr_scheduler_type linear --logging_strategy steps --logging_steps 10 --max_steps 100 --training_data_path benchmark_outputs/data/cache.json --per_device_train_batch_size 4 --output_dir benchmark_outputs/exp_64/hf --skip_memory_metrics False
```
#### Patching Summary
```
***** FMS AccelerationFramework *****
Active Plugin: AutoGPTQAccelerationPlugin. Python package: fms_acceleration_peft. Version: 0.1.0.1.dev0.
Active Plugin: FastQuantizedPeftAccelerationPlugin. Python package: fms_acceleration_foak. Version: 0.1.1.dev0.
***************** Module Forwards Patching *************
Rule: mistral-cross-ent Module:                           Class: MistralForCausalLM Num:  1
Rule: mistral-qkvo-1  Module: q_proj                    Class: QuantLinear     Num: 32
Rule: mistral-qkvo-2  Module: k_proj                    Class: QuantLinear     Num: 32
Rule: mistral-qkvo-3  Module: v_proj                    Class: QuantLinear     Num: 32
Rule: mistral-qkvo-4  Module: o_proj                    Class: QuantLinear     Num: 32
Rule: mistral-rms     Module: input_layernorm           Class: MistralRMSNorm  Num: 32
Rule: mistral-rms     Module: norm                      Class: MistralRMSNorm  Num:  1
Rule: mistral-rms     Module: post_attention_layernorm  Class: MistralRMSNorm  Num: 32
Rule: mistral-rope    Module:                           Class: MistralForCausalLM Num:  1
```
#### Output
```
{'train_runtime': 406.7227, 'train_samples_per_second': 0.983, 'train_steps_per_second': 0.246, 'train_tokens_per_second': 4028.298, 'train_loss': 1.022429027557373, 'init_mem_cpu_alloc_delta': 4096, 'init_mem_gpu_alloc_delta': 0, 'init_mem_cpu_peaked_delta': 0, 'init_mem_gpu_peaked_delta': 0, 'train_mem_cpu_alloc_delta': 361041920, 'train_mem_gpu_alloc_delta': 126487040, 'train_mem_cpu_peaked_delta': 0, 'train_mem_gpu_peaked_delta': 8758768128, 'before_init_mem_cpu': 3124195328, 'before_init_mem_gpu': 4747321344, 'epoch': 0.15}
```

#### Patching applied to GPTQ FSDP matches
Replaced a local patch for FSDP GPTQ-LORA that modified tensors to float parameters for FSDP sharding. Without this patch, the FSDP wrapping inside `accelerate.prepare` will throw an error during `trainer.train`.

```
export ACCELERATION_FRAMEWORK_CONFIG_FILE=/workspace/fms-acceleration/scripts/benchmarks/../../sample-configurations/accelerated-peft-autogptq-sample-configuration.yaml
accelerate launch --config_file scripts/benchmarks/accelerate.yaml --num_processes=2 --main_process_port=29500 -m tuning.sft_trainer --model_name_or_path TheBloke/Mistral-7B-v0.1-GPTQ --packing True --max_seq_len 4096 --learning_rate 2e-4 --fp16 True --torch_dtype float16 --peft_method lora --r 16 --lora_alpha 16 --lora_dropout 0.1 --target_modules q_proj k_proj v_proj o_proj --use_flash_attn True --response_template '
### Response:' --dataset_text_field output --include_tokens_per_second True --num_train_epochs 1 --gradient_accumulation_steps 1 --gradient_checkpointing True --evaluation_strategy no --save_strategy no --weight_decay 0.01 --warmup_steps 10 --adam_epsilon 1e-4 --lr_scheduler_type linear --logging_strategy steps --logging_steps 10 --max_steps 100 --training_data_path benchmark_outputs/data/cache.json --per_device_train_batch_size 2 --output_dir benchmark_outputs/exp_61/hf --skip_memory_metrics False
```

Output
```
***************** Module Forwards Patching *************
Rule: autogptq_distributed_tensors_as_parameters Module: base_layer                Class: QuantLinear     Num: 128
Rule: autogptq_distributed_tensors_as_parameters Module: down_proj                 Class: QuantLinear     Num: 32
Rule: autogptq_distributed_tensors_as_parameters Module: gate_proj                 Class: QuantLinear     Num: 32
Rule: autogptq_distributed_tensors_as_parameters Module: up_proj                   Class: QuantLinear     Num: 32
```

2024-07-18 13:04 UTC, fabianlim commented on plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py
> +        load_foak_patches(base_type = self._base_layer)
is there a better name then `load_foak_patches`?

2024-07-18 13:05 UTC, fabianlim commented on plugins/framework/tests/test_model_patcher.py
> +    ModelPatcher.rules.pop(DUMMY_RULE_ID, None)
why is this pop needed?

2024-07-18 13:06 UTC, fabianlim commented on plugins/framework/tests/test_model_patcher.py
> +    ModelPatcher.rules.pop(DUMMY_RULE_ID, None)
if its to changeout the rules, then better to follow the `instantiate framwork` https://github.com/foundation-model-stack/fms-acceleration/blob/main/plugins/framework/src/fms_acceleration/utils/test_utils.py

2024-07-19 01:50 UTC, fabianlim commented on plugins/framework/tests/test_model_patcher.py
> +        # can apply modifications to module here
this one you should do it like a spy. see the spy mocks in fms-hf-training https://github.com/foundation-model-stack/fms-hf-tuning/blob/main/tests/acceleration/test_acceleration_framework.py#L74-L78

2024-07-19 02:46 UTC, fabianlim commented on plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py
> +        load_foak_patches(base_type = self._base_layer)
dont import here, as there is no need to guard this import

2024-07-19 03:21 UTC, fabianlim commented on plugins/framework/src/fms_acceleration/utils/test_utils.py
> +    def __init__(self, hidden_size, *args, **kwargs) -> None:
shouldnt place this here, since this will be installed in a package.

2024-07-19 03:26 UTC, fabianlim commented on plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
> +    # Register patch
have a more descriptive name here

2024-07-20 03:49 UTC, fabianlim commented on plugins/framework/src/fms_acceleration/utils/test_utils.py
> +def instantiate_model_patcher():
you need to handle the patching history also.

2024-07-21 11:38 UTC, achew010 commented
@fabianlim This is the test plan that i'm using to write the unit test cases.

#### Test Plan

Objective:
- Ensure ModelPatcher features produces the right outputs
- Test the constraints of ModelPatcher, ModelPatcherRule, ModelPatcherTrigger and exceptions raised

**1. ModelPatcherHistory**

- Test ModelPatcherHistory Construction
    - `test_mp_history_constructs_successfully()`

**2. ModelPatcherTrigger**

- Test Trigger Construction
    - `test_mp_trigger_constructs_successfully()`
- is_triggered
    - Test Trigger checks respond as intended
        - `test_mp_trigger_returns_correct_response()`
- combine_triggers
    - `test_correct_output_combine_mp_triggers()`

**3. ModelPatcherRule**

- Test ModelPatcherRule Construction
    - `test_mp_rule_constructs_successfully()`

**4. ModelPatcher**

- combine_functions
    - `test_correct_outputs_mp_combine_functions()`
- patch_target_module
    - `test_standalone_import_and_reload_function_replaces_indirect_module`
- register behaviour
    - `test_mp_registers_only_one_unique_rule()`
- patch scenarios
    - Simple forward replacement
        - `test_mp_rule_patches_forward`
    - import_and_reload replacement
        - `test_MP_rule_import_and_reload_patches_downstream_module()`
    - forward builder replacement
        - `test_MP_rule_patches_forward_with_builder_and_args`

- summary behaviour
    - `test_mp_history_converts_to_dataframe`
- load_patches behaviour
    - `test_registration_of_rules_through_package_imports`

2024-07-25 23:01 UTC, fabianlim requested changes
1. rename test_model_pactcher.py -> test_model_patcher_helpers.py
2. rename test_model_patcher2.py -> test_model_patcher.py
3. run an unassisted bench on 7b for related bech scenarios that use model patcher.

2024-07-29 04:31 UTC, fabianlim commented on plugins/framework/src/fms_acceleration/model_patcher.py
> +        if len(_with_reload)>1:
spacing

2024-07-29 04:32 UTC, fabianlim commented on tox.ini
> +    TRITON_ALLOW_NON_CONSTEXPR_GLOBALS=1
can you put a link to where the documentation says this must be set.

2024-07-29 09:14 UTC, merged